server:
  port: 9999

easy:
  pay:
    #支付宝支付参数配置
    alipay:
      #应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
      appId:
      #商户私钥，您的PKCS8格式RSA2私钥
      privateKey:
      publicKey:
      #服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
      notifyUrl: http://f0e48dca.ngrok.io/alipay/callback
      #页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
      returnUrl: http://f0e48dca.ngrok.io
    #微信支付参数配置
    wxpay:
      #公众号appid
      appId:
      #商户id
      mchId:
      #支付api安全密钥
      mchKey:
      #支付结果回调地址
      payNotify: http://0b228e36.ngrok.io/wx/callback
      #退款结果回调(该值暂时还未使用到，因为退款我并没有做回调，待以后完善吧)
      refundNotify:
      #项目根目录根目录下的证书名称(退款需要用到证书)
      certName: wx_pay_cert.p12